### ISSUE TITLE
Different board designs?

### ISSUE THREAD

**Issue by resynth** [ctag-fh-kiel/ctag-face-2-4#5]
I'm trying to work out how to setup a CTAG face cape (as sold by Bela) in a non-standard way.  As my enclosure does not have space to stack the boards I wish to mount side by side with connectors between the headers of the Beaglebone Black and the headers of the CTAG face cape.  To do this I require a pin out or schematic for the CTAG face.  
The CTAG hackaday page directed me here but after getting confused over the schematic it seems the files here relate to a different board or an older revision.  Is that the case?
I've been looking but this github repo is all I can find, are the drawings for the newer board somewhere else or are they closed source?

**Comment by ctag-fh-kiel** [comment]
You can find it here: https://github.com/ctag-fh-kiel/bela-ctag

**Comment by resynth** [comment]
Brilliant, thankyou
